spring.application.name=server
server.servlet.context-path=/api/v1
server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/inventory_db?createDatabaseIfNotExist=true}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secretKey=${JWT_SECRET_KEY:baufbaiwefaweufeaiufavisbvsdipisdnvaskjvskvpofpowaejrfposdkvnalsdvbafjbkujfewoifjwaajsbdifuauifbvdoivnoiehgoihervbikfbaiub}
jwt.expiration=${JWT_EXPIRATION:3600000}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.application.name=server
server.servlet.context-path=/api/v1
server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/inventory_db?createDatabaseIfNotExist=true}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secretKey=${JWT_SECRET_KEY:baufbaiwefaweufeaiufavisbvsdipisdnvaskjvskvpofpowaejrfposdkvnalsdvbafjbkujfewoifjwaajsbdifuauifbvdoivnoiehgoihervbikfbaiub}
jwt.expiration=${JWT_EXPIRATION:3600000}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true 

app.cors.origin=${APP_CORS_ORIGIN:http://localhost:3000}
app.cors.origins=${APP_CORS_ORIGINS:http://localhost:3000}

jwt.expiration=3600000
